# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_tool_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'llm_tool_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16llm_tool_service.proto\x12\x10llm_tool_service\">\n\x10ToolQueryRequest\x12\x12\n\nquery_text\x18\x01 \x01(\t\x12\x16\n\x0emax_new_tokens\x18\x02 \x01(\x05\"P\n\x11ToolQueryResponse\x12\x15\n\rresponse_text\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t2f\n\x07LlmTool\x12[\n\x10ProcessToolQuery\x12\".llm_tool_service.ToolQueryRequest\x1a#.llm_tool_service.ToolQueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_tool_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOOLQUERYREQUEST']._serialized_start=44
  _globals['_TOOLQUERYREQUEST']._serialized_end=106
  _globals['_TOOLQUERYRESPONSE']._serialized_start=108
  _globals['_TOOLQUERYRESPONSE']._serialized_end=188
  _globals['_LLMTOOL']._serialized_start=190
  _globals['_LLMTOOL']._serialized_end=292
# @@protoc_insertion_point(module_scope)
