# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import llm_tool_service_pb2 as llm__tool__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in llm_tool_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LlmToolStub(object):
    """Service definition for an LLM acting as a callable tool
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessToolQuery = channel.unary_unary(
                '/llm_tool_service.LlmTool/ProcessToolQuery',
                request_serializer=llm__tool__service__pb2.ToolQueryRequest.SerializeToString,
                response_deserializer=llm__tool__service__pb2.ToolQueryResponse.FromString,
                _registered_method=True)


class LlmToolServicer(object):
    """Service definition for an LLM acting as a callable tool
    """

    def ProcessToolQuery(self, request, context):
        """Processes a query intended for a specialized LLM tool
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmToolServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessToolQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessToolQuery,
                    request_deserializer=llm__tool__service__pb2.ToolQueryRequest.FromString,
                    response_serializer=llm__tool__service__pb2.ToolQueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm_tool_service.LlmTool', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llm_tool_service.LlmTool', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LlmTool(object):
    """Service definition for an LLM acting as a callable tool
    """

    @staticmethod
    def ProcessToolQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm_tool_service.LlmTool/ProcessToolQuery',
            llm__tool__service__pb2.ToolQueryRequest.SerializeToString,
            llm__tool__service__pb2.ToolQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
